//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BigRedEntities : DbContext
    {
        public BigRedEntities()
            : base("name=BigRedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_PPA_User> tbl_PPA_User { get; set; }
        public virtual DbSet<tblWorkstation_Config> tblWorkstation_Config { get; set; }
        public virtual DbSet<tbl_Maintenance_MachineBreakdown> tbl_Maintenance_MachineBreakdown { get; set; }
    }
}
