//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int EmployeeNumber { get; set; }
        public string emp_name { get; set; }
        public int department_id { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string position { get; set; }
    }
}
