//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class line_map
    {
        public int line_map_id { get; set; }
        public int line_id { get; set; }
        public string map { get; set; }
        public Nullable<bool> red { get; set; }
        public Nullable<bool> green { get; set; }
        public Nullable<bool> yellow { get; set; }
        public Nullable<bool> blue { get; set; }
        public string issues { get; set; }
    }
}
