//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class line
    {
        public int department_id { get; set; }
        public int line_id { get; set; }
        public string line_name { get; set; }
        public string location { get; set; }
    
        public virtual department department { get; set; }
    }
}
