//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Maintenance_MachineBreakdown
    {
        public int BId { get; set; }
        public string Area { get; set; }
        public string MachineID { get; set; }
        public string Description { get; set; }
        public string Urgency { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string State { get; set; }
        public string Dates { get; set; }
        public Nullable<System.DateTime> Com_Date { get; set; }
        public Nullable<System.DateTime> St_Date { get; set; }
        public string Department { get; set; }
        public string SpareParts { get; set; }
        public string Technicians { get; set; }
        public string JobValidation { get; set; }
        public Nullable<int> T_Minutes { get; set; }
        public string Feedback { get; set; }
        public string From { get; set; }
        public string Factory { get; set; }
        public string Recorded { get; set; }
        public string other { get; set; }
        public string To { get; set; }
        public string Attachment { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
        public Nullable<System.DateTime> RecordedDate { get; set; }
        public string Category { get; set; }
    }
}
