//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_issue_feedback
    {
        public int issue_feedback_id { get; set; }
        public Nullable<int> issue_occurrence_id { get; set; }
        public Nullable<int> EmployeeNumber { get; set; }
        public Nullable<int> call_send { get; set; }
        public Nullable<int> call_answered { get; set; }
        public Nullable<int> sms_send { get; set; }
        public Nullable<int> email_send { get; set; }
    }
}
