//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Metadata
    {
        public byte[] timestamp { get; set; }
        public System.Guid User_SID { get; set; }
        public int Page_ID { get; set; }
        public string Personalization_ID { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Time { get; set; }
        public byte[] Page_Metadata_Delta { get; set; }
    }
}
