//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string User_Name { get; set; }
        public string Password { get; set; }
        public string Administration { get; set; }
        public string Calibration { get; set; }
        public string Reports { get; set; }
        public string User_Previlage { get; set; }
        public string Working_Line { get; set; }
        public Nullable<int> Emp_ID { get; set; }
        public string email { get; set; }
        public string Full_Name { get; set; }
        public byte[] Photo { get; set; }
        public string TCO_user_Code { get; set; }
        public string User_Level { get; set; }
        public string Location { get; set; }
    }
}
