// <auto-generated />
namespace IssueManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class ims2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ims2));
        
        string IMigrationMetadata.Id
        {
            get { return "202411260427536_ims2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
